JS Feedback
JohannaLin/visual-novel pull request #1
Opened 2022-05-16 18:53 UTC by JohannaLin

Created new js file with an array of objects for adventure page and started to style homepage

2022-05-24 18:49 UTC, VikoDroid requested changes

2022-05-24 18:49 UTC, VikoDroid commented on pages/adventure/adventure.js
> +  foregroundImage.setAttribute(src, foregroundImage);
Esto lo probaste? `src` representa una variable en este caso. Relee como funciona [setAttribute](https://developer.mozilla.org/en-US/docs/Web/API/Element/setAttribute).

2022-05-24 18:49 UTC, VikoDroid commented on pages/adventure/adventure.js
> +const foregroundImage = document.getElementById('foreground');
Tenes dos variables distintas llamadas `backgroundImage` y dos llamadas `foregroundImage`. Diria que estas se llamen `backgroundImageDom` y `foregroundImageDom` o algo asi.

2022-05-25 18:13 UTC, JohannaLin commented on pages/adventure/adventure.js
> +  foregroundImage.setAttribute(src, foregroundImage);
No, no lo probé. Busqué en internet y vi que se usaba para cambiar atributos con otros valores, en uno de los ejemplos lo hacían con href. Veré como hacerlo y cambiarlo entonces

2022-05-27 03:24 UTC, VikoDroid commented on pages/adventure/adventure.js
> +}
Con el ultimo cambio, `populateDom` no representa lo que pide el ticket. Por que creaste las varaibles de la linea 63 a la 67?

2022-07-04 14:42 UTC, VikoDroid approved these changes
Esta muy bien! Hay un error que vamos a corregir en otro PR.

2022-07-04 14:42 UTC, VikoDroid commented on pages/adventure/adventure.js
> +    foregroundImageDom.setAttribute("src", `${foregroundImage}`); //cambia el src del elemento (cambia el foreground)
La interpolacion esta de mas.

```suggestion
    foregroundImageDom.setAttribute("src", foregroundImage); //cambia el src del elemento (cambia el foreground)
```

2022-07-04 14:42 UTC, VikoDroid commented on pages/adventure/adventure.js
> +  backgroundImageDom.setAttribute("src", `${backgroundImage}`);
La interpolacion esta de mas.

```suggestion
  backgroundImageDom.setAttribute("src", backgroundImage);
```

2022-07-04 14:42 UTC, VikoDroid commented on pages/adventure/adventure.js
> +    if (foregroundImageDom.classList.contains("hidden") == true) { //si existe una clase CSS que oculta el elemento y existe foreground, quita la clase CSS
Esto no hace falta.

```suggestion
    if (foregroundImageDom.classList.contains("hidden")) { //si existe una clase CSS que oculta el elemento y existe foreground, quita la clase CSS
```

2022-07-05 18:18 UTC, merged